const NAME_SPACE = 'Home';

export const FETCH_HOME = `${NAME_SPACE}/FETCH_HOME`;
export const FETCH_HOME_SUCCESS = `${NAME_SPACE}/FETCH_HOME_SUCCESS`;
export const FETCH_HOME_FAIL = `${NAME_SPACE}/FETCH_HOME_FAIL`;
